modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "black_archive"
version = "${version}"
displayName = "Black Archive"
authors = "SpectrumFATM, Endertrekkie, Jeryn99"
description = '''
Adding a whole new world of alien technology to Minecraft!
'''
#logoFile = ""

[[dependencies.black_archive]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.black_archive]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.black_archive]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
